services:
  vps:
    build: .
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:2222:22"
    environment:
      - WEB_USER=admin
      - WEB_PASSWORD=admin123 # ПОМЕНЯЙ!
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      
    remnanode:
    container_name: remnanode
    hostname: remnanode
    image: remnawave/node:latest
    network_mode: host
    restart: always
    cap_add:
      - NET_ADMIN
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    environment:
      - NODE_PORT=14879
      - SECRET_KEY="eyJub2RlQ2VydFBlbSI6Ii0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLVxuTUlJQmZUQ0NBU09nQXdJQkFnSUhBWGlFUm9GekpEQUtCZ2dxaGtqT1BRUURBakF0TVNzd0tRWURWUVFERENKQ1xuU0RWTGQzaFFkMjFyYWxWNVpDMWxSWEpITWpkVWVHSnhRakJLUW1oa2FtdGZNQjRYRFRJMk1Ea3dNekUwTkRZMVxuTjFvWERUSTVNRGt3TXpFME5EWTFOMW93SXpFaE1COEdBMVVFQXhNWWRHSkZOVlpyUTNKdWVXUjJNVms0ZVdaMVxuY3pSTVpGUnJNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUUwb01iYVJ6MGZHS1VIMW1icm93Y1xuUWdheXh6aXdGQWJjeGpSVFhvUGUxVkRMa0ZEM1hjei9kS1dwODdDWEdiNW5LNkVBZm42S3pRWmhXbXp0aGpYQVxuMXFNNE1EWXdEQVlEVlIwVEFRSC9CQUl3QURBT0JnTlZIUThCQWY4RUJBTUNCYUF3RmdZRFZSMGxBUUgvQkF3d1xuQ2dZSUt3WUJCUVVIQXdFd0NnWUlLb1pJemowRUF3SURTQUF3UlFJaEFLWmhvUXBKM3M3TUxqRXROOFVEUXV2dlxuNUY4S0huL28yMTA5NC9abHVrMTJBaUJDU0ZVakdHank0cmtEa0ptVDIreUVUcDRWemlLTUlQNUFHbm9JM3d2dVxuOVE9PVxuLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLSIsIm5vZGVLZXlQZW0iOiItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZzlmSjJhWXNndmpPeWhHdTdcbkV0a3BYS2RVUWpKeHNEYzRiNm1HWFJ5eHAzK2hSQU5DQUFUU2d4dHBIUFI4WXBRZldadXVqQnhDQnJMSE9MQVVcbkJ0ekdORk5lZzk3VlVNdVFVUGRkelA5MHBhbnpzSmNadm1jcm9RQitmb3JOQm1GYWJPMkdOY0RXXG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tIiwiY2FDZXJ0UGVtIjoiLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tXG5NSUlCYXpDQ0FSS2dBd0lCQWdJQkFUQUtCZ2dxaGtqT1BRUURBakF0TVNzd0tRWURWUVFERENKQ1NEVkxkM2hRXG5kMjFyYWxWNVpDMWxSWEpITWpkVWVHSnhRakJLUW1oa2FtdGZNQjRYRFRJMU1USXlOVEExTXpNek9Gb1hEVE0xXG5NVEl5TlRBMU16TXpPRm93TFRFck1Da0dBMVVFQXd3aVFrZzFTM2Q0VUhkdGEycFZlV1F0WlVWeVJ6STNWSGhpXG5jVUl3U2tKb1pHcHJYekJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCR0VXQTQzaW5ybVZXMVQzXG5rT3BQWHhLUVRkbEFaYVVOVzFLWXVwK2c0VU9tMVRjTFIvWkxHZm1FRExqbUlvcURsdnRkQ3NSVUxJOEZCaXR4XG5ZanM4QzAyakl6QWhNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdLRU1Bb0dDQ3FHXG5TTTQ5QkFNQ0EwY0FNRVFDSUN6UDI5cjlUNmlwRWJSWEdpUktwTGZIVVRteUVwdUlQT3ZFSHA4eFczZW1BaUJBXG5NUmpDWU9hbERWb3prVlJDZzJVeTJaT2UrajhUZVBqVGZOWlFWeW1ncVE9PVxuLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLSIsImp3dFB1YmxpY0tleSI6Ii0tLS0tQkVHSU4gUFVCTElDIEtFWS0tLS0tXG5NSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXRQRHF6cm1LVzN1R3N5SGhCN2JNXG5ESWlkYnN4L1BKa0xYbTFMN0ttakxTNXBYL3NnZFpLKzJtMFcrTEVoWVVDWHdSZnQzVHdLU3NZM0RlR0pQaWtqXG5lRHlCTTl5aUcya2FIU1BMZzJQV1NqME1XTWw3eUsrY2JueGtPWm5jK1lYd2ZicEJsN3o5c0FCajRJaGVFRWdnXG54WTJYTWlMNTI4akJOd2hJMS9ydHduT3p5RC9oQ25GUjRDZ2NQRzFjQ2VsMCtIQk9LeHVPMDR2d21mOTNEQXFTXG5CTjNxS21na0trcWVSTkdrd2FSMFpjRXZNZjk4MTVrQm45cVhUN09jTTl3K0ZhRWc3S2xrVFl2QzNsVkZiaS9LXG5RYzZ1UjhyRDVFaWNZSjFrb0MvdHFYYkcvQnhNQm1iZ0lIeGExam5MWXpGTTFhTUltNkRXbVlrNWhRNWtBNXJ6XG42d0lEQVFBQlxuLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tXG4ifQ=="
